name: Build

on: [push, pull_request]

jobs:
  lint:
    name: "Lint with black & flake8"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - uses: "psf/black@stable"
      - name: "Run flake8"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade flake8
          python -m flake8 readpaf.py

  package:
    name: "Build & verify package"
    runs-on: "ubuntu-latest"
    needs: "lint"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: "Install build, check-wheel-content, and twine"
        run: "python -m pip install build twine check-wheel-contents"
      - name: "Build package"
        run: "python -m build --sdist --wheel ."
      - name: "List result"
        run: "ls -l dist"
      - name: "Check wheel contents"
        run: "check-wheel-contents dist/*.whl"
      - name: "Check long_description"
        run: "python -m twine check dist/*"

  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    needs: "package"
    strategy:
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "pypy2", "pypy3"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade pytest
      - name: "Test readpaf"
        run: |
          python -m pip install .
          python -m pytest tests/test_readpaf.py
      - name: "Test readpaf with pandas"
        run: |
          python -m pip install .[pandas]
          python -m pytest tests/test_dataframe.py

  coverage:
    name: "Run Coverage"
    runs-on: "ubuntu-latest"
    needs: "tests"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade pytest pytest-cov
          python -m pip install .
          python -m pytest --cov=readpaf --cov-report term tests/test_readpaf.py
          python -m pip install .[pandas]
          python -m pytest --cov=readpaf --cov-report term tests/test_dataframe.py

  upload:
    if: startsWith( github.ref, 'refs/tags/' )
    name: "Publish package to PyPI"
    runs-on: "ubuntu-latest"
    needs: "tests"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: "Install build, check-wheel-content, and twine"
        run: "python -m pip install build twine check-wheel-contents"
      - name: "Build package"
        run: "python -m build --sdist --wheel ."
      - name: "List result"
        run: "ls -l dist"
      - name: "Check wheel contents"
        run: "check-wheel-contents dist/*.whl"
      - name: "Check long_description"
        run: "python -m twine check dist/*"
      - name: "Upload"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
