name: Publish

on: 
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  publish:
    name: "Publish package to PyPI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install build, check-wheel-content, and twine"
        run: "python -m pip install build twine check-wheel-contents"
      - name: "Build package"
        run: "python -m build --sdist --wheel ."
      - name: "List result"
        run: "ls -l dist"
      - name: "Check wheel contents"
        run: "check-wheel-contents dist/*.whl"
      - name: "Check long_description"
        run: "python -m twine check dist/*"
      - name: "Upload"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
